Promo/urls.py
from django.urls import path

from .views import *


app_name = 'Promo'

urlpatterns = [
     path('', buatpromo, name='Buat_Promo') ,
    # path('', list_promo, name='Buat_Promo') ,
    # path('Buat_Admin/', buatpromo, name='buatpromo') ,
    # path('buat_promoHS/', buat_HS, name='buat_promoHS') ,
    path("Baca_Admin", list_promo, name ='Baca_Admin'),
    path('detail/<str:id>', detailpromo, name='detail_promo'),
    path('ubah/<str:id>', ubahpromo, name='ubah_promo'),
     path('delete/<str:id>', deletepromo, name='delete_promo'),
    path('buat_HS/', buat_HS, name='buat_promoHS') ,
    path('buat_MT/', buat_MT, name='buat_promoMT') ,
    path("Baca_Restaurant", list_promo, name ='Baca_Restaurant'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('restopay/', include('restopay.urls')),
    path('jam_operasional/', include('jam_operasional.urls')),
     path('transaksi_pesanan/', include('transaksi_pesanan.urls')),
    path('kategori_makanan/', include('kategori_makanan.urls')),
    path('tarifPengiriman/', include('tarifPengiriman.urls')),
    path('Makanan/', include('Makanan.urls')),
    path('authentication/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kategori_restoran/', include('kategori_restoran.urls')),
    path('bahan_makanan/', include('bahan_makanan.urls')),
    path('Riwayat/', include('Riwayat.urls')),
    path('Promo/', include('Promo.urls')),
    path('PromoRestoran/', include('PromoRestoran.urls')),
]

urlpatterns += staticfiles_urlpatterns()

Promo/models.py
from decimal import Decimal
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
PERCENTAGE_VALIDATOR = [MinValueValidator(0), MaxValueValidator(100)]
from django.db import connection

class promo:
    def __init__(self, id, name, quantity,jenis, tanggal = None,mintrans = None):
        self.id = id
        self.name = name
        self.quantity = quantity
        self.tanggal = tanggal
        self.mintrans = mintrans
        self.jenis = jenis
        self.used = False

class PromoRepository:
    def get_all(self):
        cursor = connection.cursor()
        queryHS = f"""SELECT * FROM promo natural join special_day_promo;"""
        cursor.execute(queryHS)
        rows = cursor.fetchall()
        categories = []
        i = 0
        for row in rows:
            categories.append(promo(row[0], row[1],row[2],"Special Day Promo" ))
            categories[i].tanggal = row[3]
            i += 1

        queryMT = f"""SELECT * FROM promo natural join min_transaction_promo;"""
        cursor.execute(queryMT)
        rows = cursor.fetchall()
    
        for row in rows:
            categories.append(promo(row[0], row[1],row[2],"Promo Minimum Transaksi"))
            categories[i].mintrans = row[3]
            i+=1
        
        used_id = []
        queryused = f"""SELECT pid FROM restaurant_promo;"""

        
        
        cursor.execute( queryused)
        rows = cursor.fetchall()
        
        for row in rows:
            used_id.append(row[0])
            
        for category in categories:
            if category.id in used_id:
                category.used = True
                
        return categories
    
    def insertHS(self, name, quantity, tanggal):
        print("MAsuk")
        cursor = connection.cursor()
        cursor.execute(f"SELECT count(id) from promo")
        countangka = cursor.fetchall()
        cursor.execute(f"SELECT id from promo")
        idangka = cursor.fetchall()
        print(countangka)
        # idbaru = countangka[0][0] + 2
        id = countangka[0][0] 
        while (id in idangka) :
            id += 1
        idbaru = id

        query = f"""INSERT INTO promo (id,promoname, discount) VALUES ( '{idbaru}','{name}', '{quantity}');"""
        cursor.execute(query)
        query = f"""INSERT INTO special_day_promo (id,date) VALUES ('{idbaru}','{tanggal}');"""
        cursor.execute(query)
    
    def insertMT(self, name, quantity, mintrans):
        cursor = connection.cursor()
        cursor.execute(f"SELECT count(id) from promo")
        countangka = cursor.fetchall()
        print(countangka)
        # idbaru = countangka[0][0] + 2
        cursor.execute(f"SELECT id from promo")
        idangka = cursor.fetchall()
        print(countangka)
        # idbaru = countangka[0][0] + 2
        id = countangka[0][0] 
        while (id in idangka) :
            id += 1
        idbaru = id
        print(idbaru)
        query = f"""INSERT INTO promo (id,promoname, discount) VALUES ( '{idbaru}','{name}', '{quantity}');"""
        cursor.execute(query)
        query = f"""INSERT INTO min_transaction_promo (id,minimumtransactionnum) VALUES ('{idbaru}','{mintrans}');"""
        cursor.execute(query)
        # query = f"""INSERT INTO min_transaction_promo (minimumtransactionnum) VALUES ('{mintrans}');"""

    def ubah(self,id,tanggal_awal,mintrans_awal,kuantitas,tanggal,mintrans):
        cursor = connection.cursor()
        if (tanggal_awal  == None):
           
         query1 = f"""update  promo set discount = '{kuantitas}' where id = '{id}';"""
         cursor.execute(query1)

         query2 = f"""update min_transaction_promo set minimumtransactionnum = '{mintrans}' where id = '{id}';"""
         cursor.execute(query2)
        else :
            query1 = f"""update promo set discount = '{kuantitas}' where id = '{id}';"""
            cursor.execute(query1)
    
            query2 = f"""update special_day_promo set date = '{tanggal}' where id = '{id}';"""
            cursor.execute(query2)
        

    def detail_promo(self, id):
        cursor = connection.cursor()
        get_query = f"""SELECT * FROM promo where promo.id = '{id}';"""
        cursor.execute(get_query)
        rows = cursor.fetchall()

        print( rows)

        queryHS = f"""SELECT id FROM special_day_promo;"""
        queryMT = f"""SELECT id FROM min_transaction_promo;"""
        
        cursor.execute( queryHS)
        
        rowsHS = cursor.fetchall()
        # cursor.execute(queryMT)
        
        # rowsMT = cursor.fetchall()

        idHS = []
        # idMT = []
        promotjan = []
        for row in rowsHS:
            idHS.append(row[0])
        # for row in rowsMT:  
        #     idMT.append(row[0])     
        for row in rows :
            if row[0] in idHS :
                queryHS = f"""SELECT * FROM promo natural join special_day_promo where 
                promo.id = '{id}';"""
                cursor.execute( queryHS)
                rowHS = cursor.fetchall()[0]

    
                promotjan.append(promo( rowHS[0],  rowHS[1], rowHS[2],"Special Day Promo" ))
                promotjan[0].tanggal =  rowHS[3]
            else :

                queryMT = f"""SELECT * FROM promo natural join min_transaction_promo where 
                promo.id = '{id}';"""
                cursor.execute( queryMT)
                rowMT = cursor.fetchall()[0]
                # print(rowsMT)

                promotjan.append(promo(rowMT[0], rowMT[1],rowMT[2], "Promo Minimum Transaksi"))
                promotjan[0].mintrans = rowMT[3]

        return promotjan

#  for rowHS in rowsHS:
#                     promotjan.append(promo( rowHS[0],  rowHS[1], rowHS[2],"Special Day Promo" ))
#                     promotjan.tanggal =  rowHS[3]
#             else :

#                 queryMT = f"""SELECT * FROM promo natural join min_transaction_promo where 
#                 promo.id = '{id}';"""
#                 cursor.execute( queryMT)
#                 rowsMT = cursor.fetchall()
#                 print(rowsMT)

#                 for rowMT in rowsMT:
#                     promotjan.append(promo(rowMT[0], rowMT[1],rowMT[2], "Promo Minimum Transaksi"))
#                     promotjan.mintrans = rowMT[3]

        return promotjan
            
    def delete_promo(self, id):
        cursor = connection.cursor()

        used_id = []
        queryHS = f"""SELECT id FROM special_day_promo;"""

        cursor.execute( queryHS)
        rowsHS = cursor.fetchall()
        for row in rowsHS:
            used_id.append(row[0])

        if id in used_id:
            query = f"""DELETE FROM special_day_promo WHERE id = '{id}';"""
            cursor.execute(query)
        else:
            query = f"""DELETE FROM min_transaction_promo WHERE id = '{id}';"""
            cursor.execute(query)

        query =f"DELETE FROM promo WHERE id = '{id}';"
        cursor.execute(query)

   

Promo/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
# from rest_framework.fields import JSONField
# from rest_framework.utils import json
from django.db import connection
from .models import *
from django.views.generic import ListView, DetailView,TemplateView,View
# Create your views here.
# Create your views here.
from itertools import chain
from authentication.models import *


def list_promo(request) :
    # role = request.session.get('role')
     if 'user_email' not in request.session:
        return redirect('/authentication/login')
        
     uar = UserAccRepository()
     if( uar.isAdmin(request.session.get('user_email'))):
        promo_repo = PromoRepository()
        categories = promo_repo.get_all()
        context = {"Promolist" : categories}
        return render(request, 'Baca_Admin.html', context)

     elif ( uar.isRestaurant(request.session.get('user_email'))): 
        promo_repo = PromoRepository()
        categories = promo_repo.get_all()
        context = {"Promolist" : categories}
        return render(request, 'Baca_Restaurant.html', context)
     else :
        return redirect('/authentication/login')


def buat_HS(request) :
    if 'user_email' not in request.session:
        return redirect('/authentication/login')
    
    uar = UserAccRepository()    

    if( not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')
    if request.method == "POST":
        nama_promo = request.POST.get("nama_promo")
        kuantitas =  request.POST.get("kuantitas")
        if (kuantitas  == ""):
            messages.info(request, "Data yang diisikan belum lengkap, silakan lengkapi data terlebih dahulu.")
        else :
            kuantitas = int(kuantitas)
            if (kuantitas < 1 or kuantitas > 100) :
                 messages.info(request, "persentase diskon harus di antara 1 hingga 100")
        tanggal = request.POST.get("tanggal")
        if (nama_promo == "" or tanggal == ""):
            messages.info(request, "Data yang diisikan belum lengkap, silakan lengkapi data terlebih dahulu.")
        

        else:
            promo_repo = PromoRepository()

            # if (promo_repo.check_promo(nama_promo) == True) :
            #     messages.info(request, "Nama Promo sudah ada, silakan gunakan nama promo yang lain")
            promo_repo.insertHS(nama_promo,kuantitas,tanggal)
            # category_repo = FoodCategoryRepository()
            # category_repo.add_category(nama_kategori)
            return redirect("Promo:Baca_Admin")
            # return render(request, 'Buat_PromoHS.html',)
    else :
        return render(request, 'Buat_PromoHS.html')


def buat_MT(request) :
    if 'user_email' not in request.session:
        return redirect('/authentication/login')
    
    uar = UserAccRepository()    
    
    if( not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    if request.method == "POST":
        nama_promo = request.POST.get("nama_promo")
        kuantitas =  request.POST.get("kuantitas")
        if (kuantitas  == ""):
            messages.info(request, "Data yang diisikan belum lengkap, silakan lengkapi data terlebih dahulu.")
        else :
            kuantitas = int(kuantitas)
            if (kuantitas < 1 or kuantitas > 100) :
                 messages.info(request, "persentase diskon harus di antara 1 hingga 100")
        mintrans = request.POST.get("mintrans")
        if (nama_promo == "" or mintrans== ""):
            messages.info(request, "Data yang diisikan belum lengkap, silakan lengkapi data terlebih dahulu.")
        

        else:
            promo_repo = PromoRepository()

            # if (promo_repo.check_promo(nama_promo) == True) :
            #     messages.info(request, "Nama Promo sudah ada, silakan gunakan nama promo yang lain")
            promo_repo.insertMT(nama_promo,kuantitas,mintrans)
            # category_repo = FoodCategoryRepository()
            # category_repo.add_category(nama_kategori)
            return redirect("Promo:Baca_Admin")
            # return render(request, 'Buat_PromoHS.html',)
    else :
        return render(request, 'Buat_PromoMT.html')

def detailpromo(request,id) :
    if 'user_email' not in request.session:
        return redirect('/authentication/login')
    
    uar = UserAccRepository()    
    
    # if( not uar.isAdmin(request.session.get('user_email')) or not uar.isRestaurant(request.session.get('user_email')) ):
    
    #     return redirect('/authentication/login')
   
    promo_repo = PromoRepository()
    promo = promo_repo.detail_promo(id)
    context = {"promolist" : promo}
    
    print(promo[0].id)
    return render(request, 'Detail_Promo2.html', context)

def ubahpromo(request,id) :
    if 'user_email' not in request.session:
        return redirect('/authentication/login')
    
    uar = UserAccRepository()    
    
    if( not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    promo_repo = PromoRepository()
    promo = promo_repo.detail_promo(id)
    context = {"promolist" : promo}
    print(promo)
    if (request.method == "POST"):
        id = promo[0].id
        tanggal_awal = promo[0].tanggal
        mintrans_awal = promo[0].mintrans
        kuantitas =  request.POST.get("kuantitas")
        tanggal = request.POST.get("tanggal")
        mintrans = request.POST.get("mintrans")
        print("masuk")
        promo_repo.ubah(id,tanggal_awal,mintrans_awal,kuantitas,tanggal,mintrans)

        return redirect("Promo:Baca_Admin")
    else :

        return render(request,'ubah_promo.html',context)

def buatpromo(request) :
    return render(request, 'menu.html',)

# def detailpromo2(request) :
#     return render(request, 'Detail_Promo2.html')
def deletepromo(request,id) :
    if 'user_email' not in request.session:
        return redirect('/authentication/login')
    
    uar = UserAccRepository()    
    
    if( not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    promo_repo = PromoRepository()
    promo_repo.delete_promo(id)
    # context = {"promolist" : promo}
    
    # print(promo[0].id)
    return redirect("Promo:Baca_Admin")

Promo/templates/Baca_Admin.html
<!DOCTYPE html>
{% extends 'base.html' %}

    <body>
      {% block content %}
      <h1 > Daftar Promo (POV Admin)<br> </h1>
        
        
    <<table class = "table bordered-table"> >
      <thead class="table-success">
        <tr>
          <th scope="col">No</th>
          <th scope="col">Nama Promo</th>
          <th scope="col">Jenis Promo</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for promo in Promolist %}
           <tr>
           <th scope="row">{{ forloop.counter }}</th>
           <td>{{promo.name}}</td>
           <td>{{promo.jenis}}</td>
           {% if promo.used %}
             <td><a class="pe-auto" href="{% url 'Promo:ubah_promo' promo.id%}">Ubah</a><br> <a class="pe-auto" href="{% url 'Promo:detail_promo' promo.id%}">detail</a>
           {% else %}
             <td><a class="pe-auto"href="{% url 'Promo:ubah_promo' promo.id%}">Ubah</a><br> <a class="pe-auto" href="{% url 'Promo:detail_promo' promo.id%}">detail</a><br> <a class="pe-auto" href="{% url 'Promo:delete_promo' promo.id%}">hapus</a></td>
           {% endif %}
        {% endfor %}
       </tbody>
   </table>
  
    {% endblock %}
    </body>

Promo/templates/Baca_Restaurant.html
<!DOCTYPE html>
{% extends 'base.html' %}

    <body>
      {% block content %}
    <h1 > Daftar Promo (POV Restaurant)<br> </h1>
    <!-- <h3 > <a href="url">[Tambah  Promo ]</a> </h3> -->
        
        
    <<table class = "table bordered-table"> >
      <thead class="table-success">
        <tr>
          <th scope="col">No</th>
          <th scope="col">Nama Promo</th>
          <th scope="col">Jenis Promo</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for promo in Promolist %}
           <tr>
           <th scope="row">{{ forloop.counter }}</th>
           <td>{{promo.name}}</td>
           <td>{{promo.jenis}}</td>
           {% if promo.used %}
             <td> <a class="pe-auto" href="{% url 'Promo:detail_promo' promo.id%}">detail</a>
           {% else %}
             <td> <a class="pe-auto" href="{% url 'Promo:detail_promo' promo.id%}">detail</a></td>
           {% endif %}
        {% endfor %}
       </tbody>
   </table>
  
    {% endblock %}
    </body>

Promo/templates/Buat_promoHS.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% block content %}
<h1 > Buat Promo Special Day <br> </h1>
<form method="post" action="">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Nama Promo : </label>
    <input type="text" class="form-control" id="nama_promo" name= "nama_promo" aria-describedby="emailHelp" placeholder="Enter promo">
    
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Discount (%) : </label>
    <input type="number" class="form-control" id="kuantitas" name= "kuantitas" placeholder="enter discount">
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Tanggal Berlangsung : </label>
    <input type="date" class="form-control" id="tanggal" name="tanggal" aria-describedby="emailHelp" placeholder="Enter date">
    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
  </div>
  <button type="submit" class="btn btn-primary">Simpan</button>
</form>
{% endblock %}

Promo/templates/Buat_promoMT.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% block content %}
<form method="post" action="">
  {% csrf_token %}
  <div class="form-group">
    <label for="exampleInputEmail1">Nama Promo : </label>
    <input type="text" class="form-control" id="nama_promo" name= "nama_promo" aria-describedby="emailHelp" placeholder="Enter promo">
    
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Discount (%) : </label>
    <input type="number" class="form-control" id="kuantitas" name= "kuantitas" placeholder="enter discount">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Minimal Transaksi : </label>
    <input type="number" class="form-control" id="mintrans" name= "mintrans" placeholder="enter min.transaksi">
  </div>
  <button type="submit" class="btn btn-primary">Simpan</button>
</form>
{% endblock %}

Promo/templates/Detail_MinimumTransaksi2_Promo.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Phoenix editor</title>
        <link rel="stylesheet" href="styles.css" />
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,500,600,800"
            rel="stylesheet" />
                <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>

    <body>
  <form>
  <div class="form-group">
    <label class="mr-sm-2" for="inlineFormCustomSelect">Jenis Promo</label>
      <p type="text" class="form-control" id="inlineFormCustomSelect" >Promo Minimum Transaksi</p>
    </div>
    <div class="form-group">
    <label for="formGroupExampleInput">NamaPromo</label>
    <p type="text" class="form-control" id="formGroupExampleInput" > B3LANJA 3 AJA    </p>
  </div>
  <div class="form-row align-items-center">
    <div class="col-auto my-1">
           <div class="col-md-6 col-sm-6 col-xs-12"> 
            <label for="quantity">Jumlah Diskon (1 hingga 100 ):</label>
            <p type="number" class="form-control" id="quantity" > 30</p>
        </div>
        
   <div class="bootstrap-iso">
 <div class="container-fluid">
  <div class="row">
   <div class="col-md-6 col-sm-6 col-xs-12">
       <label for="tanggal"> Minimum Transaksi: </label>
        <!-- <input type="date" id="Start Date" name="Start Date"> -->
        <p type="number" class="form-control" id="tanggal" > 3</p>
 </div>
    </div>
  </div>
      
</form>
        
    </body>
</html>

Promo/templates/Detail_Promo.html
{% extends 'base.html' %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <title>detail_promo</title>
        <link rel="stylesheet" href="styles.css" />
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,500,600,800"
            rel="stylesheet" />
                <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>

    <body>
  <!-- <form> -->
    {% for promo in promolist %}
  <div class="form-group">
    <label class="mr-sm-2" for="inlineFormCustomSelect">Jenis Promo</label>
      <span><p type="text" class="form-control" id="inlineFormCustomSelect" > {{promo.jenis}}</p></span>
    </div>
    <div class="form-group">
    <label for="formGroupExampleInput">NamaPromo</label>
    <p type="text" class="form-control" id="formGroupExampleInput" > {{promo.name}}</p>
  </div>
  <div class="form-row align-items-center">
    <div class="col-auto my-1">
           <div class="col-md-6 col-sm-6 col-xs-12"> 
            <label for="quantity">Jumlah Diskon (1 hingga 100 ):</label>
            <p type="number" class="form-control" name ="kuantitas" id="quantity" > {{promo.kuantitas}}</p>
        </div>
  {% if promo.tanggal %}
    <div class="container-fluid">
      <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12">
          <label for="tanggal"> Tanggal mulai Transaksi: </label>
            <p type="date" class="form-control" id="tanggal" > {{promo.tanggal}}</p>
    </div>
        </div>
      </div>
  {% else %}
    <div class="container-fluid">
      <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-12">
          <label for="mintrans"> Minimum Transaksi: </label>
            <p type="number" class="form-control" id="tanggal" > {{promo.mintrans}}</p>
    </div>
        </div>
      </div>
  {% endif %}

  {% endfor %}
  <div><button><a href="{% url 'Promo:Baca_Admin' %}" ></a>Kembali</button></div>

  
</form>
      
    </body>
</html>

Promo/templates/Detail_Promo2.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% block content %}
{% for promo in promolist %}
<style> p.solid {border-style: solid;}</style>
<form>
  <div class="form-group">
    <label for="formGroupExampleInput">Nama Promo  : </label>
    <span><p class = "solid">{{promo.name}}</p></span>
  </div>

  <div class="form-group">
    <label for="formGroupExampleInput">Jenis Promo  : </label>
    <span><p class = "solid">{{promo.jenis}}</p></span>
  </div>

  <div class="form-group">
    <label for="formGroupExampleInput">Jumlah diskon  : </label>
    <span><p type = "number" class = "solid">{{promo.quantity}}</p></span>
  </div>
  {% if promo.tanggal %}
  <div class="form-group">
    <label for="formGroupExampleInput">Tanggal Hari Spesial  : </label>
    <span><p type = "number" class = "solid">{{promo.tanggal}}</p></span>
  </div>

  {% else %}
  <div class="form-group">
    <label for="formGroupExampleInput">Minimal Transaksi  : </label>
    <span><p type = "number" class = "solid">{{promo.mintrans}}</p></span>
  </div>
  {% endif %}
  <!-- <div class="form-group">
    <label for="formGroupExampleInput2">Another label</label>
    <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input">
  </div> -->
  <button><a href="{% url 'Promo:Baca_Admin'%}">Kembali</a></button>
</form>
{% endfor %}
{% endblock %}

Promo/templates/menu.html
<!DOCTYPE html>
{% extends 'base.html' %}

    <body>
      {% block content %}
    <h1 > Promo Sirest <br> </h1>
    <h3 > <a href="{% url 'Promo:Baca_Admin' %}">[Daftar Promo]</a> </h3>
    <h3 > <a href="{% url 'Promo:buat_promoHS' %}">[Tambah  Promo Special Day ]</a> </h3>
    <h3 > <a href="{% url 'Promo:buat_promoMT' %}">[Tambah  Promo Min Transaksi ]</a> </h3>
    <!-- <h3 > <a href="{% url 'Promo:Baca_Restaurant' %}">[Daftar Promo (Restaurant)]</a> </h3> -->

    {% endblock %}

Promo/templates/ubah_promo.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% block content %}
{% for promo in promolist %}
<style> p.solid {border-style: solid;}</style>
<form method="POST" action="">
    {% csrf_token %}
    <div class="form-group row">
      <label for="staticEmail" class="col-sm-2 col-form-label">Nama Promo : </label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext" id="staticEmail" value={{promo.name}}>
      </div>
    </div>

    <div class="form-group row">
        <label for="staticEmail" class="col-sm-2 col-form-label">Jenis Promo : </label>
        <div class="col-sm-10">
          <input type="text" readonly class="form-control-plaintext" id="staticEmail" value={{promo.jenis}}>
        </div>
    </div>
    <div class="form-group row">
      <label for="inputPassword" class="col-sm-2 col-form-label">Jumlah discount : </label>
      <div class="col-sm-10">
        <input type="number" class="form-control" id="kuantitas" placeholder="kuantitas" name = "kuantitas">
      </div>
    </div>
    {% if promo.tanggal %}
    <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">Tanggal Berlangsung : </label>
        <div class="col-sm-10">
          <input type="date" class="form-control" id="tanggal" placeholder="tanggal" name = "tanggal">
        </div>
    </div>
    {% else %}
    <div class="form-group row">
        <label for="inputPassword" class="col-sm-2 col-form-label">Minimal Transaksi : </label>
        <div class="col-sm-10">
          <input type="number" class="form-control" id="mintrans" placeholder="mintrans" name = "mintrans">
        </div>
    </div>
    {% endif %}
    <div><button type="submit">Simpan</button></div>


  </form>
{% endfor %}
{% endblock %}