Promo/urls.py
from django.urls import path

from .views import *


app_name = 'Promo'

urlpatterns = [
     path('', buatpromo, name='Buat_Promo') ,
    # path('', list_promo, name='Buat_Promo') ,
    # path('Buat_Admin/', buatpromo, name='buatpromo') ,
    # path('buat_promoHS/', buat_HS, name='buat_promoHS') ,
    path("Baca_Admin", list_promo, name ='Baca_Admin'),
    path('detail/<str:id>', detailpromo, name='detail_promo'),
    path('ubah/<str:id>', ubahpromo, name='ubah_promo'),
     path('delete/<str:id>', deletepromo, name='delete_promo'),
    path('buat_HS/', buat_HS, name='buat_promoHS') ,
    path('buat_MT/', buat_MT, name='buat_promoMT') ,
    path("Baca_Restaurant", list_promo, name ='Baca_Restaurant'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('restopay/', include('restopay.urls')),
    path('jam_operasional/', include('jam_operasional.urls')),
     path('transaksi_pesanan/', include('transaksi_pesanan.urls')),
    path('kategori_makanan/', include('kategori_makanan.urls')),
    path('tarifPengiriman/', include('tarifPengiriman.urls')),
    path('Makanan/', include('Makanan.urls')),
    path('authentication/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kategori_restoran/', include('kategori_restoran.urls')),
    path('bahan_makanan/', include('bahan_makanan.urls')),
    path('Riwayat/', include('Riwayat.urls')),
    path('Promo/', include('Promo.urls')),
    path('PromoRestoran/', include('PromoRestoran.urls')),
]

urlpatterns += staticfiles_urlpatterns()

tarifPengiriman/urls.py
from django.urls import path

from .views import *


app_name = 'tarifPengiriman'

urlpatterns = [
    path('buat_tarif/', show_buat_tarif, name='show_buat_tarif'),
    path('daftar_tarif/', show_daftar_tarif, name='show_daftar_tarif'),
    path('update_tarif/<str:id>/<str:province>', show_update_tarif, name='show_update_tarif'),
    path('update/<str:id>/<str:province>', update_tarif, name='update_tarif'),
    path('hapus_tarif/<str:id>', hapus_tarif, name="hapus_tarif"),
    path('buat_tarif_logic/', buat_tarif, name='buat_tarif'),


]

tarifPengiriman/models.py
from django.db import connection

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


class TarifPengiriman:

    def __init__(self, id, province, motorfee, carfee):
        self.id = id
        self.province = province
        self.motorfee = motorfee
        self.carfee = carfee
    
    def __str__(self):
        return f"""TarifPengiriman
                    id: {self.id} 
                    province: {self.email}
                    motorfee: {self.motorfee}
                    carfee: {self.carfee}
                    """


class TarifPengirimanRepository:

    def getAllTarifPengiriman(self):
        cursor = connection.cursor()
        query = f"""
                    SELECT * FROM DELIVERY_FEE_PER_KM;    
                """ 

        cursor.execute(query)

        tarif_pengiriman_objects = dictfetchall(cursor)

        list_tarif_pengiriman = []
        for i in range(len(tarif_pengiriman_objects)):
            tarif_pengiriman = TarifPengiriman(tarif_pengiriman_objects[i]['id'], tarif_pengiriman_objects[i]['province'], 
                                            tarif_pengiriman_objects[i]['motorfee'], tarif_pengiriman_objects[i]['carfee'])
            list_tarif_pengiriman.append(tarif_pengiriman)

        # print(list_tarif_pengiriman)

        return list_tarif_pengiriman


    def createTarifPengiriman(self, province, motorfee, carfee):
        
        cursor = connection.cursor()
        
        query = f"""
                    SELECT * FROM DELIVERY_FEE_PER_KM;    
                """ 

        cursor.execute(query)

        banyak_tarif_pengiriman = len(dictfetchall(cursor))


        query = f"""
                    INSERT INTO DELIVERY_FEE_PER_KM
                    VALUES ('{banyak_tarif_pengiriman}','{province}', {motorfee} , {carfee});
                    ;    
                """ 
        
        
        try:
            cursor.execute(query)
            return True
            
        except Exception as error:
            return error
    


    def updateTarifPengiriman(self, id, new_motorfee, new_carfee):

        cursor = connection.cursor()
        query = f"""
                    UPDATE DELIVERY_FEE_PER_KM
                    SET motorfee= {new_motorfee}, carfee= {new_carfee} 
                    WHERE id= '{id}'
                    ;    
                """ 
        
        
        try:
            cursor.execute(query)
            return True
            
        except Exception as error:
            return error

    def hapusTarifPengiriman(self, id):

        cursor = connection.cursor()
        query = f"""
                    DELETE FROM DELIVERY_FEE_PER_KM
                    WHERE id= '{id}'
                    ;    
                """ 
        try:
            cursor.execute(query)
            return True
        except Exception as e:
            return e
            
            

tarifPengiriman/views.py
from django.shortcuts import render

from urllib import request

from django.shortcuts import redirect

from django.contrib import messages

from django.contrib import auth

from django.contrib.auth.decorators import login_required

import datetime

from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.urls import reverse

from django.core import serializers

from django.utils.decorators import method_decorator

from authentication.models import *

from .models import *

# Create your views here.
def show_buat_tarif(request, message=False):

    if 'user_email' not in request.session:
        return redirect('/authentication/login')
        
    uar = UserAccRepository()
    if(not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    context = {'error_msg': message}
    return render(request, "buat_tarif.html", context)


def buat_tarif(request):

    if 'user_email' not in request.session:
        return redirect('/authentication/login')
    
    uar = UserAccRepository()
    if(not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    if request.method == "POST":

        province = request.POST["province"]
        motorfee = request.POST["motorfee"]
        carfee = request.POST["carfee"]

        if province == "" or motorfee == "" or carfee == "":
            return show_buat_tarif(request, "Data yang diisikan belum lengkap, silakan lengkapi data terlebih dahulu.")


        tarif_repo = TarifPengirimanRepository()
        queryResult = tarif_repo.createTarifPengiriman(province, motorfee, carfee)
        print(queryResult)

    
    if type(queryResult) == bool:
        return redirect('/tarifPengiriman/daftar_tarif/')
    else:
        return show_buat_tarif(request, queryResult)


def show_daftar_tarif(request, error_msg=False):

    if 'user_email' not in request.session:
        return redirect('/authentication/login')

    uar = UserAccRepository()
    if(not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    tarif_repo = TarifPengirimanRepository()
    list_tarif_pengiriman = tarif_repo.getAllTarifPengiriman()
    

    context = {'list_tarif_pengiriman' : list_tarif_pengiriman,
    'error_msg' : error_msg}

    return render(request, "daftar_tarif.html", context)


def show_update_tarif(request, id, province, msg=False):


    if 'user_email' not in request.session:
        return redirect('/authentication/login')

    uar = UserAccRepository()
    if(not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    context = { 'id' : id, 
                'province': province,
                'error_msg': msg
                }
    return render(request, "update_tarif.html", context)

def update_tarif(request, id, province):
    if 'user_email' not in request.session:
        return redirect('/authentication/login')

    uar = UserAccRepository()
    if(not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')


    if request.method == "POST":
        new_motorfee = request.POST["motorfee"]
        new_carfee = request.POST["carfee"]

        if new_motorfee == "" or new_carfee == "":
            return show_update_tarif(request, id, province, "Data yang diisikan belum lengkap, silakan lengkapi data terlebih dahulu.")

        tarif_repo = TarifPengirimanRepository()
        queryResult = tarif_repo.updateTarifPengiriman(id, int(new_motorfee), int(new_carfee))

    if type(queryResult) == bool:
        return redirect('/tarifPengiriman/daftar_tarif/')
    else:
        return show_update_tarif(request, id, province, queryResult)


def hapus_tarif(request, id):
    if 'user_email' not in request.session:
        return redirect('/authentication/login') 
    
    uar = UserAccRepository()
    
    if(not uar.isAdmin(request.session.get('user_email'))):
        return redirect('/authentication/login')

    if request.method == "POST":
        tarif_repo = TarifPengirimanRepository()
        
        queryResult = tarif_repo.hapusTarifPengiriman(id)

        return show_daftar_tarif(request, queryResult)

tarifPengiriman/templates/buat_tarif.html
{% include 'navbarAdmin.html' %}

{% load static %}

{% block meta %}
<title>Buat Tarif</title>
<style>
  *{
    margin: 5px;

  }
</style>
{% endblock meta %}

{% block content %}

<div class="text-center">
  <h1>Buat Tarif Pengiriman</h1>
</div>

{% if error_msg %}
  <h2>{{error_msg}}</h2>
{% endif %}

<form  action="{% url 'tarifPengiriman:buat_tarif' %}" method="POST">
  {% csrf_token %}
    
    <div class="mb-3">
      <label for="provinsi" class="form-label" >Provinsi: </label>
      <input type="text" class="form-control" id="provinsi" name="province">
      <div id="provinsiHelp" class="form-text"></div>
    </div>
    
    <div class="mb-3">
      <label for="tarif-motor" class="form-label">Tarif Motor: </label>
      <input type="number" class="form-control" id="tarif-motor" name="motorfee">
    </div>

        
    <div class="mb-3">
      <label for="tarif-motor" class="form-label">Tarif Mobil: </label>
      <input type="number" class="form-control" id="tarif-mobil" name="carfee">
    </div>
    
    <button type="submit" class="btn btn-primary">Simpan</button>

</form>

{% endblock content %}

tarifPengiriman/templates/daftar_tarif.html
{% include 'navbarAdmin.html' %}

{% load static %}


{% block meta %}
<title>Daftar Tarif</title>
<style>
  *{
    margin: 5px;

  }
</style>
{% endblock meta %}

{% if error_msg %}
  <h2>{{error_msg}}</h2>
{% endif %}

{% block content %}
  
<div class="text-center">

  <h1 >Daftar Tarif Pengiriman</h1>
</div>


<table class="table table-bordered">
        
        <thead>
          <td>No</td>
          <td>Provinsi</td>
          <td>Biaya Motor</td>
          <td>Biaya Mobil</td>
          <td>Aksi</td>
        </thead>


        {% for tarif_pengiriman in list_tarif_pengiriman %}
        <tbody>
          <tr class="">
            <td>{{forloop.counter}}</td>
            <td>{{tarif_pengiriman.province}}</td>
            <td>{{tarif_pengiriman.motorfee}}</td>
            <td>{{tarif_pengiriman.carfee}}</td>
            <td>
              <a href="{% url 'tarifPengiriman:show_update_tarif' tarif_pengiriman.id tarif_pengiriman.province %}">Ubah</a>
              <br>
              <form action="{% url 'tarifPengiriman:hapus_tarif' tarif_pengiriman.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Hapus">
              </form>
            </td>
          </tr>
          
        </tbody>
        {% endfor %}  

  </table>

{% endblock content %}

tarifPengiriman/templates/update_tarif.html
{% include 'navbarAdmin.html' %}

{% load static %}

{% block meta %}
<title>Update Tarif</title>
<style>
  *{
    margin: 5px;

  }
</style>
{% endblock meta %}

{% block content %}


<div class="text-center">

  <h1 >Update Tarif Pengiriman</h1>
</div>


{% if error_msg %}
  <h2>{{error_msg}}</h2>
{% endif %}

<form  action="{% url 'tarifPengiriman:update_tarif' id province %}" method="POST">
  {% csrf_token %}
    
    <div class="mb-3">
      <label for="provinsi" class="form-label" >Provinsi: </label>
      <input type="text" class="form-control" id="provinsi" name="province" disabled value={{province}}>
      <div id="provinsiHelp" class="form-text"></div>
    </div>
    
    <div class="mb-3">
      <label for="tarif-motor" class="form-label">Tarif Motor: </label>
      <input type="number" class="form-control" id="tarif-motor" name="motorfee">
    </div>

        
    <div class="mb-3">
      <label for="tarif-motor" class="form-label">Tarif Mobil: </label>
      <input type="number" class="form-control" id="tarif-mobil" name="carfee">
    </div>
    
    <input type="submit" value="Simpan">

</form>

{% endblock content %}