Makanan/urls.py
from django.urls import path

from .views import *


app_name = 'Makanan'

urlpatterns = [
    path('buat_makanan/', show_buat_makanan, name='show_buat_makanan'),
    path('buat_makanan-logic/', buat_makanan, name='buat_makanan'),

    path('daftarMakanan_restoView/', show_makanan_restoView, name='show_makanan_restoView'),
    
    path('update_makanan/<str:FoodName>/', show_update_makanan, name='show_update_makanan'),
    path('update_makanan-logic/<str:FoodName>/', update_makanan, name='update_makanan'),

    path('daftarMakanan_nonRestoView/<str:rname>/<str:rbranch>/', show_makanan_nonRestoView, name='show_makanan_nonRestoView'),

    path('detail_resto/<str:rname>/<str:rbranch>/', show_detail_resto, name='show_detail_resto'),
    
    path('daftar_restoran/', show_daftar_restoran, name='show_daftar_restoran'),
    

    path('hapus_makanan/<str:FoodName>/', hapus_makanan, name='hapus_makanan'),




]

Promo/urls.py
from django.urls import path

from .views import *


app_name = 'Promo'

urlpatterns = [
     path('', buatpromo, name='Buat_Promo') ,
    # path('', list_promo, name='Buat_Promo') ,
    # path('Buat_Admin/', buatpromo, name='buatpromo') ,
    # path('buat_promoHS/', buat_HS, name='buat_promoHS') ,
    path("Baca_Admin", list_promo, name ='Baca_Admin'),
    path('detail/<str:id>', detailpromo, name='detail_promo'),
    path('ubah/<str:id>', ubahpromo, name='ubah_promo'),
     path('delete/<str:id>', deletepromo, name='delete_promo'),
    path('buat_HS/', buat_HS, name='buat_promoHS') ,
    path('buat_MT/', buat_MT, name='buat_promoMT') ,
    path("Baca_Restaurant", list_promo, name ='Baca_Restaurant'),
]

kategori_makanan/urls.py
from django.urls import path
from kategori_makanan.views import *

app_name = "kategori_makanan"

urlpatterns = [
    path('', show_kategori_makanan, name='show_kategori_makanan'),
    path('tambah/', show_tambah_kategori_makanan, name='show_tambah_kategori_makanan'),
    path('hapus/<str:id>', delete_kategori_makanan, name='delete_kategori_makanan'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('restopay/', include('restopay.urls')),
    path('jam_operasional/', include('jam_operasional.urls')),
     path('transaksi_pesanan/', include('transaksi_pesanan.urls')),
    path('kategori_makanan/', include('kategori_makanan.urls')),
    path('tarifPengiriman/', include('tarifPengiriman.urls')),
    path('Makanan/', include('Makanan.urls')),
    path('authentication/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kategori_restoran/', include('kategori_restoran.urls')),
    path('bahan_makanan/', include('bahan_makanan.urls')),
    path('Riwayat/', include('Riwayat.urls')),
    path('Promo/', include('Promo.urls')),
    path('PromoRestoran/', include('PromoRestoran.urls')),
]

urlpatterns += staticfiles_urlpatterns()

tarifPengiriman/urls.py
from django.urls import path

from .views import *


app_name = 'tarifPengiriman'

urlpatterns = [
    path('buat_tarif/', show_buat_tarif, name='show_buat_tarif'),
    path('daftar_tarif/', show_daftar_tarif, name='show_daftar_tarif'),
    path('update_tarif/<str:id>/<str:province>', show_update_tarif, name='show_update_tarif'),
    path('update/<str:id>/<str:province>', update_tarif, name='update_tarif'),
    path('hapus_tarif/<str:id>', hapus_tarif, name="hapus_tarif"),
    path('buat_tarif_logic/', buat_tarif, name='buat_tarif'),


]

transaksi_pesanan/urls.py
from django.urls import path
from transaksi_pesanan.views import *

app_name = 'transaksi_pesanan'

urlpatterns = [
    # resto
    path('', p_berlangsung, name='rpesanan_index'),
    # path('detail/', p_detail, name='rpesanan_detail'),
    path('add_status/', p_addstatus, name='rpesanan_confirm'),
    # pelanggan
    path('tambah/', tambah_transaksi, name="tambah_transaksi"),
    path('pilih_restoran/', pilih_restoran, name="pilih_restoran"),
    path('pilih_makanan/', pilih_makanan, name="pilih_makanan"),
    path('daftar_pesanan_pelanggan/', daftar_pesanan_pelanggan, name="daftar_pesanan_pelanggan"),
    path('konfirmasi_pembayaran/', konfirmasi_pembayaran, name='konfirmasi_pembayaran'),
    path('ringkasan_pesanan/', ringkasan_pesanan, name='ringkasan_pesanan'),
    path('pesanan_berlangsung_pelanggan/', pesanan_berlangsung_pelanggan, name='pesanan_berlangsung_pelanggan'),
    path('detail_pesanan_pelanggan/', detail_pesanan_pelanggan, name='detail_pesanan_pelanggan'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
      crossorigin="anonymous"
    />
    {% block meta %} {% endblock meta %}
  </head>

  <body>
    {% block content %} {% endblock content %}
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js"
      integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/navbarAdmin.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Admin</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Dashboard</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
          >
            Restoran
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="#">Daftar Kategori Restoran</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Buat Kategori Restoran</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'kategori_makanan:show_tambah_kategori_makanan' %}">Daftar Kategori Makanan</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'kategori_makanan:show_kategori_makanan' %}">Buat Kategori Makanan</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Daftar Bahan Makanan</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Buat Bahan Makanan</a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'Makanan:show_daftar_restoran' %}">Daftar Restoran dan Makanan</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Promo
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'Promo:Baca_Restaurant' %}">Daftar Promo</a></li>
            <li><a class="dropdown-item" href="/Riwayat/">Buat Promo</a></li>
            <li><hr class="dropdown-divider" /></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Pesanan
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'tarifPengiriman:show_daftar_tarif' %}"
                >Daftar Tarif Pengiriman per KM</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'tarifPengiriman:show_buat_tarif' %}">Buat Tarif Pengiriman per KM</a>
            </li>
            <li><hr class="dropdown-divider" /></li>
          </ul>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock content %}

templates/navbarKurir.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Kurir</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Dashboard</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Makanan:show_daftar_restoran' %}">Daftar Restoran dan Makanan</a>
        </li>


        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Pesanan
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="#">Pesanan Berlangsung</a>
            </li>
            <li><a class="dropdown-item" href="#">Riwayat Pesanan</a></li>
            <li><hr class="dropdown-divider" /></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/Riwayat/">Riwayat</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'restopay-index' %}">RestoPay</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% endblock content %}

templates/navbarPelanggan.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Pelanggan</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/authentication/logged_customer/">Dashboard</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Makanan:show_daftar_restoran' %}">Daftar Restoran dan Makanan</a>
        </li>


        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Pesanan
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'transaksi_pesanan:tambah_transaksi' %}">Buat Pesanan</a></li>
            <li>
              <a class="dropdown-item" href="{% url 'transaksi_pesanan:pesanan_berlangsung_pelanggan' %}">Pesanan Berlangsung</a>
            </li>
            <li><a class="dropdown-item" href="#">Riwayat Pesanan</a></li>
            <li><hr class="dropdown-divider" /></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/Riwayat/">Riwayat</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'restopay-index' %}">RestoPay</a>
        </li>


        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

{% endblock content %}

templates/navbarRestoran.html
{% extends 'base.html' %} {% block content %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Restoran</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/authentication/logged_restaurant/">Dashboard</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="{% url 'jam_daftar' %}"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Jam Operasional
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <a class="dropdown-item" href="{% url 'jam_daftar' %}">Daftar Jam Operasional </a>
            </li>
            <li><a class="dropdown-item" href="{% url 'jam_buat' %}">Buat Jam Operasional</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Makanan
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'Makanan:show_makanan_restoView' %}">Daftar Makanan </a></li>
            <li><a class="dropdown-item" href="{% url 'Makanan:show_buat_makanan' %}">Buat Makanan</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Pesanan
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/transaksi_pesanan/">Pesanan Berlangsung</a></li>
            <li><a class="dropdown-item" href="#">Riwayat Pesanan</a></li>
          </ul>
        </li>
        

        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Promo
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'Promo:Baca_Restaurant' %}">Daftar Promo Tersedia</a></li>
            <li><a class="dropdown-item" href="#">Daftar Promo Restoran</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/Riwayat/">Riwayat</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'restopay-index' %}">RestoPay</a>
        </li>

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endblock content %}