Promo/urls.py
from django.urls import path

from .views import *


app_name = 'Promo'

urlpatterns = [
     path('', buatpromo, name='Buat_Promo') ,
    # path('', list_promo, name='Buat_Promo') ,
    # path('Buat_Admin/', buatpromo, name='buatpromo') ,
    # path('buat_promoHS/', buat_HS, name='buat_promoHS') ,
    path("Baca_Admin", list_promo, name ='Baca_Admin'),
    path('detail/<str:id>', detailpromo, name='detail_promo'),
    path('ubah/<str:id>', ubahpromo, name='ubah_promo'),
     path('delete/<str:id>', deletepromo, name='delete_promo'),
    path('buat_HS/', buat_HS, name='buat_promoHS') ,
    path('buat_MT/', buat_MT, name='buat_promoMT') ,
    path("Baca_Restaurant", list_promo, name ='Baca_Restaurant'),
]

Riwayat/urls.py
from django.urls import path

from .views import *


app_name = 'Riwayat'

urlpatterns = [
    # path('', Baca_RiwayatTransaksiPemesananPelanggan, name='Baca_RiwayatTransaksiPemesanan') ,
    # path('Baca_RiwayatTransaksiPemesananRestoran/', Baca_RiwayatTransaksiPemesananRestoran, name='Baca_RiwayatTransaksiPemesananRestoran') ,
    # path('Baca_RiwayatTransaksiPemesananKurir/', Baca_RiwayatTransaksiPemesananKurir, name='Baca_RiwayatTransaksiPemesananKurir')  ,
    # path('Form_Penilaian_Pemesanan/', Form_Penilaian_Pemesanan, name='Form_Penilaian_Pemesanan') , 
    # path('Detail_Pemesanan/', Detail_Pemesanan, name='Detail_Pemesanan') ,
    path('', tabel, name='tabel'),
    path('back', tabel, name='back'),
    # path('tabel_P/', tabel_P, name='tabel_P'),
    # path('tabel_K/', tabel_K, name='tabel_K'),
    path('detail/<email>/<datetime>', detail_riwayat, name='detail'),

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('restopay/', include('restopay.urls')),
    path('jam_operasional/', include('jam_operasional.urls')),
     path('transaksi_pesanan/', include('transaksi_pesanan.urls')),
    path('kategori_makanan/', include('kategori_makanan.urls')),
    path('tarifPengiriman/', include('tarifPengiriman.urls')),
    path('Makanan/', include('Makanan.urls')),
    path('authentication/', include('authentication.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('kategori_restoran/', include('kategori_restoran.urls')),
    path('bahan_makanan/', include('bahan_makanan.urls')),
    path('Riwayat/', include('Riwayat.urls')),
    path('Promo/', include('Promo.urls')),
    path('PromoRestoran/', include('PromoRestoran.urls')),
]

urlpatterns += staticfiles_urlpatterns()

Riwayat/models.py
from django.db import models

# Create your models here.

Riwayat/views.py
from django.shortcuts import render
from django.shortcuts import redirect



from authentication.models import *
from authentication.views import *
from django.db import connection
# Create your views here.
# def Baca_Pelanggan(request):
#     # current_user = auth.get_user(request)
#     cursor = connection.cursor()
from authentication.models import *

class table_R :
    def __init__(self, email, pfname, plname,kfname, klname, datetime, name, rating):
        self.email = email
        self.pfname = pfname
        self.plname = plname
        self.kfname = kfname
        self.klname = klname
        self.datetime = datetime
        self.name = name
        self.rating = rating
class table_P :
    def __init__(self, email, rname, rbranch,kfname, klname, datetime, name, rating):
        self.email = email
        self.rname = rname
        self.rbranch = rbranch
        self.kfname = kfname
        self.klname = klname
        self.datetime = datetime
        self.name = name
        self.rating = rating
class table_K :
    def __init__(self, email, rname, rbranch,pfname, plname, datetime, name, rating):
        self.email = email
        self.rname = rname
        self.rbranch = rbranch
        self.pfname = pfname
        self.plname = plname
        self.datetime = datetime
        self.name = name
        self.rating = rating
def tabel(request):
    cursor = connection.cursor()
    if 'user_email' not in request.session:
        return redirect('/authentication/login')
        
    uar = UserAccRepository()
    if(uar.isRestaurant(request.session.get('user_email'))):
        # return redirect('/authentication/login')
        email = request.session.get('user_email')
        restaurandb = RestaurantRepository()
        restaurant = restaurandb.getByEmail(email)
        daftar_R = []
        querytable1 = f'''
            select t.email, cus.fname , cus.lname, cur.fname,cur.lname, t.datetime, ts.name, t.rating
            from transaction t,
            (Select us.email, us.fname,us.lname from user_acc us natural join customer ) as cus,
            (Select use.email, use.fname,use.lname from user_acc use natural join courier ) as cur,
            transaction_food tf,
            transaction_history th, transaction_status ts
            where t.email = cus.email and t.courierid = cur.email and (t.email, t.datetime) = (tf.email, tf.datetime)
            and (t.email, t.datetime) = (th.email, th.datetime) and th.tsid = ts.id and ts.id in ('TS_STAT003') and tf.rname = '{restaurant.rname}' and tf.rbranch = '{restaurant.rbranch}';'''

        cursor.execute(querytable1)
        hasil1 = cursor.fetchall()

        i = 0
        for row in hasil1 :
            daftar_R.append(table_R(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7]))
            i+=1
        
        context = { 'daftar':  daftar_R}

        return render(request, "tabel_R.html", context)
    
    elif(uar.isCustomer(request.session.get('user_email'))):
        email = request.session.get('user_email')
        customerdb = CustomerRepository()
        customer = customerdb.getByEmail(email)
        daftar_P = []

        querytable2 = f''' select t.email, tf.rname, tf.rbranch, cur.fname,cur.lname, t.datetime, ts.name, t.rating
        from transaction t,
        (Select us.email, us.fname,us.lname from user_acc us natural join customer ) as cus,
        (Select use.email, use.fname,use.lname from user_acc use natural join courier ) as cur,
        transaction_food tf,
        transaction_history th, transaction_status ts
        where t.email = cus.email and t.courierid = cur.email and (t.email, t.datetime) = (tf.email, tf.datetime)
        and (t.email, t.datetime) = (th.email, th.datetime) and th.tsid = ts.id and ts.id in ('TS_STAT004','TS_STAT006') and cus.email = '{customer.email}';'''

        cursor.execute(querytable2)
        hasil2 = cursor.fetchall()
    
        i = 0
        for row in hasil2 :
            daftar_P.append(table_P(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7]))
            i+=1
        
        context = { 'daftar':  daftar_P}

        return render(request, "tabel_P.html", context)
    
    elif(uar.isCourier(request.session.get('user_email'))):
        email = request.session.get('user_email')
        courierdb = CourierRepository()
        courier = courierdb.getByEmail(email)
        daftar_K = []
        print("masuk courie")
        querytable3 = f''' select t.email, tf.rname, tf.rbranch, cus.fname , cus.lname, t.datetime, ts.name, t.rating
        from transaction t,
        (Select us.email, us.fname,us.lname from user_acc us natural join customer ) as cus,
        (Select use.email, use.fname,use.lname from user_acc use natural join courier ) as cur,
        transaction_food tf,
        transaction_history th, transaction_status ts
        where t.email = cus.email and t.courierid = cur.email and (t.email, t.datetime) = (tf.email, tf.datetime)
        and (t.email, t.datetime) = (th.email, th.datetime) and th.tsid = ts.id and ts.id in ('TS_STAT004','TS_STAT006') and cur.email = '{courier.email}';'''

        cursor.execute(querytable3)
        hasil3 = cursor.fetchall()

        # print(hasil3[0])
        for row in hasil3 :
            # print(row[0])
            daftar_K.append(table_K(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7]))
        context = { 'daftar':  daftar_K}

        return render(request, "tabel_K.html", context)
    
    else :
        return redirect('/authentication/login')

class Detail_riwayat:
    def __init__(self, email,datetime,pfname, plname,street,district, city	,province,rname,rbranch,foodname,note,street2,district2,city2,province2, totalfood,totaldiscount	,deliveryfee ,totalprice, pmname,psname,tsname,kfname,klname,platenum,vehicletype,vehiclebrand) :
        self.email = email
        self.datetime = datetime
        self.pfname = pfname
        self.plname = plname

        self.street = street
        self.district = district
        self.city = city
        self.province = province

        self.rname  = rname
        self.rbranch = rbranch
        self.foodname = foodname
        self.note = note

        self.street2 = street2
        self.district2 = district2
        self.city2 = city2
        self.province2 = province2

        self.totalfood = totalfood
        self.totaldiscount = totaldiscount
        self.deliveryfee = deliveryfee
        self.totalprice = totalprice
        self.pmname = pmname
        self.psname = psname
        self.tsname = tsname

        self.kfname = kfname
        self.klname = klname
        self.platenum = platenum
        self.vehicletype = vehicletype
        self.vehiclebrand = vehiclebrand

class detail2 :
    def __init__(self,tsname,datetime) :
        self.tsname = tsname
        self.datetime = datetime

def detail_riwayat(request, email,datetime) :
    cursor = connection.cursor()
   
    querytable4 = f'''select t.email,t.datetime, cus.fname,cus.lname, t.street, t.district, t.city, t.province, tf.rname, tf.rbranch,tf.foodname ,tf.note,r.street,r.district,r.city,r.province, t.totalfood, t.totaldiscount, t.deliveryfee, t.totalprice, pm.name, ps.name,ts.name,
     cur.fname, cur.lname, cur.platenum, cur.vehicletype, cur.vehiclebrand
    from transaction t,
    (Select us.email, us.fname,us.lname from user_acc us natural join customer ) as cus,
    (Select * from courier natural join user_acc ) as cur,
    transaction_food tf, restaurant r,
    transaction_history th, transaction_status ts, payment_method pm, payment_status ps
    where t.email = cus.email and t.courierid = cur.email and (t.email, t.datetime) = (tf.email, tf.datetime) and t.pmid = pm.id and t.psid = ps.id
    and (t.email, t.datetime) = (th.email, th.datetime) and th.tsid = ts.id and ts.id in ('TS_STAT004','TS_STAT006') and (r.rname, r.rbranch) = (tf.rname,tf.rbranch) and t.email = '{email}' and t.datetime = '{datetime}';'''

    cursor.execute(querytable4)
    hasil4 = cursor.fetchall()
    daftar_detail = []
    i = 0
    for row in hasil4 :
        daftar_detail.append(Detail_riwayat(row[0],row[1],row[2],row[3],row[4],row[5],row[6],row[7],row[8],row[9],row[10],row[11],row[12],row[13],row[14],row[15],row[16],row[17],row[18],row[19],row[20],row[21],row[22],row[23],row[24],row[25], row[26], row[27]))
        i+=1
    querytable5 = f'''select ts.name, t.datetime
    from transaction t,
    (Select us.email, us.fname,us.lname from user_acc us natural join customer ) as cus,
    (Select * from courier natural join user_acc ) as cur,
    transaction_food tf, restaurant r,
    transaction_history th, transaction_status ts, payment_method pm, payment_status ps
    where t.email = cus.email and t.courierid = cur.email and (t.email, t.datetime) = (tf.email, tf.datetime) and t.pmid = pm.id and t.psid = ps.id
    and (t.email, t.datetime) = (th.email, th.datetime) and th.tsid = ts.id  and (r.rname, r.rbranch) = (tf.rname,tf.rbranch) and t.email = '{email}' and t.datetime = '{datetime}';'''

    cursor.execute(querytable5)
    hasil5 = cursor.fetchall()
    daftar_detail2 = []
    i = 0
    for row in hasil5 :
        daftar_detail2.append(detail2(row[0],row[1]))
        i+=1
    
    context = { 'daftar':  daftar_detail, 'daftar2': daftar_detail2}

    return render(request, "Detail.html", context)


# select t.email,t.datetime, cus.fname,cus.lname, t.street, t.district, t.city, t.province, tf.rname, tf.rbranch,tf.foodname ,t.totalfood, t.totaldiscount, t.deliveryfee, t.totalprice, pm.name, ps.name,
#      cur.fname, cur.lname, cur.platenum, cur.vehicletype, cur.vehiclebrand
#     from transaction t,
#     (Select us.email, us.fname,us.lname from user_acc us natural join customer ) as cus,
#     (Select * from courier use natural join user_acc ) as cur,
#     transaction_food tf,
#     transaction_history th, transaction_status ts
#     where t.email = cus.email and t.courierid = cur.email and (t.email, t.datetime) = (tf.email, tf.datetime)

Riwayat/templates/Baca_RiwayatTransaksiPemesananK.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Phoenix editor</title>
        
        <link rel="stylesheet" href="styles.css" />
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,500,600,800"
            rel="stylesheet" />
                <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    
    <body>
    
      <h1 > Daftar Transaksi (POV Kurir)<br> </h1>
        
        
        <table style = "border: 1px solid black;" >
  <tr style = "border: 1px solid black;">
    <th style = "border: 1px solid black;">No</th>
    <th style = "border: 1px solid black;">Restoran - Cabang</th>
    <th style = "border: 1px solid black;">Nama pelanggan</th>
    <th style = "border: 1px solid black;">Waktu Pesanan Dibuat</th>
    <th style = "border: 1px solid black;"> Status Pesanan</th>
    <th style = "border: 1px solid black;"> Aksi</th>

  </tr>
  <tr style = "border: 1px solid black;">
     <td style = "border: 1px solid black;">1</td>
     <td style = "border: 1px solid black;">Warung Mantap Depok</td>
     <td style = "border: 1px solid black;">Mikayla Putri</td>
     <td style = "border: 1px solid black;">2022-11-04 11:30:05</td>
     <td style = "border: 1px solid black;">Pesanan Selesai</td>
     <td style = "border: 1px solid black;"><a href="url">[Detail]</a><br>
      
  </tr>
</table>
    </body>

Riwayat/templates/Baca_RiwayatTransaksiPemesananP.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>Phoenix editor</title>
        
        <link rel="stylesheet" href="styles.css" />
        <link
            href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,500,600,800"
            rel="stylesheet" />
                <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    </head>
    
    <body>
    
    <h1 > Daftar Transaksi (POV Pelanggan)<br> </h1>
        
        
        <table style = "border: 1px solid black;" >
  <tr style = "border: 1px solid black;">
    <th style = "border: 1px solid black;">No</th>
    <th style = "border: 1px solid black;">Restoran</th>
    <th style = "border: 1px solid black;">Nama Kurir</th>
    <th style = "border: 1px solid black;">Waktu Pesanan Dibuat</th>
    <th style = "border: 1px solid black;"> Status Pesanan</th>
    <th style = "border: 1px solid black;"> Rating</th>
    <th style = "border: 1px solid black;"> Aksi</th>

  </tr>
  <tr style = "border: 1px solid black;">
    <td style = "border: 1px solid black;">1</td>
    <td style = "border: 1px solid black;">Warung Mantap Depok</td>
    <td style = "border: 1px solid black;">Doni Suryana</td>
    <td style = "border: 1px solid black;">2022-11-04 11:30:05</td>
    <td style = "border: 1px solid black;">Pesanan Selesai</td>
    <td style = "border: 1px solid black;"> 6</td>
    <td style = "border: 1px solid black;"><a href="url">[Detail]</a><br>
      <a href="url">[Nilai]</a><br>
      
  </tr>
  <tr style = "border: 1px solid black;">
    <td style = "border: 1px solid black;">2</td>
    <td style = "border: 1px solid black;">KFC Depok</td>
    <td style = "border: 1px solid black;"> </td>
    <td style = "border: 1px solid black;">2022-11-01 09:00:01</td>
    <td style = "border: 1px solid black;"> Pesanan Dibatalkan</td>
    <td style = "border: 1px solid black;"> - - -</td>
    <td style = "border: 1px solid black;"><a href="url">[Detail]</a><br>
      <a href="url">[Nilai]</a><br>
  </tr>
  <!-- <tr style = "border: 1px solid black;">
    <td>3</td>
    <td>RAJINMAKAN</td>
    <td>2022-08-15 s.d. 2022-08-20</td>
    <td><a href="url">[Detail]</a><br>
      <a href="url">[Ubah]</a><br>
      <a href="url">[Hapus]</a> </td>
  </tr> -->

  <!-- <tr>
    <td>4</td>
    <td>Promo 17 Agustusan</td>
    <td>2022-08-15 s.d. 2022-08-20</td>
    <td><a href="url">[Detail]</a><br>
      <a href="url">[Ubah]</a><br>
      <a href="url">[Hapus]</a> </td> -->
  </tr>
</table>
    </body>

Riwayat/templates/Detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<body>
  {% for detail in daftar%}
    <h1> Detail Pesanan </h1>
    <p> Waktu Pesanan : {{detail.datetime}} </p>
    <p> Nama Pelanggan : {{detail.pfname}} {{detail.plname}} </p>
    <p>Jalan: {{detail.street}}</p>
    <p> Kecamatan:{{detail.district}}</p>
    <p> Kota: {{detail.city}}</p>
    <p> Provinsi: {{detail.province}}</p>

    <p> Restoran: {{detail.rname}} {{detail.rbranch}} </p>
    <p> Jalan: {{detail.street2}}</p>
    <p> Kecamatan: {{detail.district2}}</p>
    <p> Kota: {{detail.city2}}</p>
    <p> Provinsi: {{detail.province2}}</p>
        
    <p>  Makanan yang dipesan: {{detail.foodname}} - {{detail.note}}</p>
    <!-- <p> Kopi Susu - Tanpa es batu</p> -->
    <p>  Total Harga Makanan: {{detail.totalfood}}</p>
    <p>  Total Diskon:{{detail.totaldiscount}}</p>
    <p>  Biaya Pengantaran: {{detail.deliveryfee}}</p>
    <p>  Total Biaya: {{detail.totalprice}}</p>
     <p>   Jenis Pembayaran: {{detail.pmname}}</p>
        
    <p>  Status Pembayaran: {{detail.psname}}</p>
    <p>  Status Pesanan: {{detail.tsname}}</p>
        
    <p>  Kurir:{{detail.kfname}} {{detail.klname}}</p>
    <p> Plat Kendaraan: {{detail.platenum}}</p>
    <p> Jenis Kendaraan: {{detail.vehicletype}}</p>
    <p> Merk Kendaraan: {{detail.vehiclebrand}}</p>
    {% endfor %}
    <table style = "border: 1px solid black;" >
        <tr style = "border: 1px solid black;">
          <th style = "border: 1px solid black;">Status</th>
          <th style = "border: 1px solid black;">TimeStamp</th>
        </tr>
        {% for detail2 in daftar2%}
        <tr style = "border: 1px solid black;">
          <td style = "border: 1px solid black;">{{detail2.tsname}}</td>
          <td style = "border: 1px solid black;">{{detail2.datetime}} </td>
        </tr>
        {% endfor %}

      </table>
       
    <button type="button" class="btn btn-primary justify-content-center"><a href="{% url 'Riwayat:back' %}">Kembali</a></button>
     

    
</body>
{% endblock content %}

Riwayat/templates/tabel_K.html
<!DOCTYPE html>
{% extends 'base.html' %}

    <body>
      {% block content %}
    <h1 > Riwayat Kurir  : <br> </h1>
    <!-- <h3 > <a href="url">[Tambah  Promo ]</a> </h3> -->
        
    <!-- <p > Daftar Promo restoran : </p>     -->
    <table class = "table bordered-table"> 
      <thead class="table-success">
        <tr>
          <th scope="col">No</th>
          <th scope="col">Nama Restoran</th>
          <th scope="col">Nama Pelanggan</th>
          <th scope="col">Waktu Pesanan Dibuat</th>
          <th scope="col">Status Pesanan</th>
          <!-- <th scope="col">Rating</th> -->
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for detail in daftar %}
           <tr>
           <th scope="row">{{ forloop.counter }}</th>
           <td>{{detail.rname}} {{detail.rbranch}}</td>
           <td>{{detail.pfname}} {{detail.plname}}</td>
           <td>{{detail.datetime}}</td>
           <td>{{detail.name}}</td>
           <!-- <td>{{detail.rating}}</td> -->
           <!-- {% if promo.used %} -->
             <!-- <td><a class="pe-auto" href="url">Ubah</a><br> <a class="pe-auto" href="url">detail</a> -->
           <!-- {% else %} -->
             <td><a class="pe-auto" href="{% url 'Riwayat:detail' detail.email detail.datetime %}">detail</a><br> </td>
           <!-- {% endif %} -->
        {% endfor %}
       </tbody>
   </table>
  
    {% endblock %}
    </body>

Riwayat/templates/tabel_P.html
<!DOCTYPE html>
{% extends 'base.html' %}

    <body>
      {% block content %}
    <h1 > Riwayat Pelanggan  : <br> </h1>
    <!-- <h3 > <a href="url">[Tambah  Promo ]</a> </h3> -->
        
    <!-- <p > Daftar Promo restoran : </p>     -->
    <table class = "table bordered-table"> 
      <thead class="table-success">
        <tr>
          <th scope="col">No</th>
          <th scope="col">Nama Restoran</th>
          <th scope="col">Nama Kurir</th>
          <th scope="col">Waktu Pesanan Dibuat</th>
          <th scope="col">Status Pesanan</th>
          <th scope="col">Rating</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for detail in daftar%}
           <tr>
           <th scope="row">{{ forloop.counter }}</th>
           <td>{{detail.rname}} {{detail.rbranch}}</td>
           <td>{{detail.kfname}} {{detail.klname}}</td>
           <td>{{detail.datetime}}</td>
           <td>{{detail.name}}</td>
           <td>{{detail.rating}}</td>
           <!-- {% if promo.used %} -->
             <!-- <td><a class="pe-auto" href="url">Ubah</a><br> <a class="pe-auto" href="url">detail</a> -->
           <!-- {% else %} -->
             <td> <a class="pe-auto" href="{% url 'Riwayat:detail' detail.email detail.datetime %}">detail</a><br> </td>
           <!-- {% endif %} -->
        {% endfor %}
       </tbody>
   </table>
  
    {% endblock %}
    </body>

Riwayat/templates/tabel_R.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% include 'navbarRestoran.html' %}
    <body>
      {% block content %}
    <h1 > Riwayat Restoran  : <br> </h1>
    <!-- <h3 > <a href="url">[Tambah  Promo ]</a> </h3> -->
        
    <!-- <p > Daftar Promo restoran : </p>     -->
    <table class = "table bordered-table"> 
      <thead class="table-success">
        <tr>
          <th scope="col">No</th>
          <th scope="col">Nama Pelanggan</th>
          <th scope="col">Nama Kurir</th>
          <th scope="col">Waktu Pesanan Dibuat</th>
          <th scope="col">Status Pesanan</th>
          <!-- <th scope="col">Rating</th> -->
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        {% for detail in daftar%}
           <tr>
           <th scope="row">{{ forloop.counter }}</th>
           <td>{{detail.pfname}} {{detail.plname}}</td>
           <td>{{detail.kfname}} {{detail.klname}}</td>
           <td>{{detail.datetime}}</td>
           <td>{{detail.name}}</td>
           <!-- <td>{{detail.rating}}</td> -->
           <!-- {% if promo.used %} -->
             <!-- <td><a class="pe-auto" href="url">Ubah</a><br> <a class="pe-auto" href="url">detail</a> -->
           <!-- {% else %} -->
             <td> <a class="pe-auto" href="{% url 'Riwayat:detail' detail.email detail.datetime %}">detail</a><br> </td>
           <!-- {% endif %} -->
        {% endfor %}
       </tbody>
   </table>
  
    {% endblock %}
    </body>